train:
  data:
    train_dir: ./data/tuples/train
    train_batch_size: 64
    test_dir: ./data/tuples/test
    test_batch_size: 64
  model:
    input_size: 773
    embedding_size: 32
    hidden_layers:
    - 1024
    - 256
    - 64
    loss: binary_crossentropy
    train_steps_per_epoch: 100
    test_steps_per_epoch: 20
    tf_callbacks: [checkpoints]
    save_dir: ./models
evaluate:
  data:
    test_dir: ./data/tuples/test
    test_batch_size: 64
    model_dir: ./models
  eval:
    number_examples: 10
    result_dir: .results
