train:
  data:
    train_dir: ./data/tensors/train
    test_dir: ./data/tensors/test
    train_batch_size: 256
    test_batch_size: 256
  model:
    save_dir: ./models
    train_steps_per_epoch: 20
    test_steps_per_epoch: 5
    loss: binary_crossentropy
    tf_callbacks: [checkpoints]
evaluate:
  data:
    model_dir: ./models
    test_dir: ./data/tensors/test
    test_batch_size: 64
  eval:
    number_examples: 10
    result_dir: ./results
